spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/boardpractice?characterEncoding=UTF-8&serverTimezone=UTCa
    username: root
    password: infotech@30
  devtools:
    remote:
      restart:
        enabled: true
